### ISSUE TITLE
role of olo:next

### ISSUE THREAD

**Issue by seebi** [vocol/scor#18]
I believe that olo:next is not used correctly at the moment. The question is what we want to achieve here. I believe ordering of Class Instances is not what we want. Instead we want to provide a method to order instances of our process classes and we want to restrict these lists in a way that a reasoner gives us an error when instances are not ordered correctly. 

We should discuss this

**Comment by np00** [comment]
I added it to allow applications to show all steps of a certain process and display them in the correct order.

Example: An incoming order is identified to go into the Stocks (Source Stocked Product). The person responsible for processing this order needs to know all steps which are involved (in the correct order).

Validating that these steps were properly executed (not skipping one or executing a wrong one) is of course useful as well.

**Comment by np00** [comment]
Example how process steps may be realized using olo ontology: https://github.com/vocol/scor/commit/4520284a4aa7bd939fc0318af3b16af8026c7fff

Please let me know if you have anything to add.

**Comment by seebi** [comment]
I'm fine with that, at least for now. (the hasStepList relation sounds a little bit strange ...

**Comment by np00** [comment]
default steplists created, olo:next removed & hasStepList changed to hasSteps: https://github.com/vocol/scor/commit/b1749a8757bfb2a7ac00234b9824b964cbaff197
