### ISSUE TITLE
define scor:hasMetric* Properties

### ISSUE THREAD

**Issue by seebi** [vocol/scor#9]
create label and base body
link correct Processes

**Comment by np00** [comment]
property definition completed: https://github.com/vocol/scor/commit/67e7102513a8fabe94df594cd44a544d7c0ab8fd
link to correct processes: https://github.com/vocol/scor/commit/5dca28d758ba59c3f19cc29b37648a79e20cad93
created label: https://github.com/vocol/scor/commit/483420a6a6ffded764075805a0791fb8ed39c429
